#FUNCIONES EMBEBIDAS

dias = ('lunes','martes','miercoles','jueves','viernes','sabado','domingo')
type(dias)
print(type(dias))
lista_dias = list(dias)
type(lista_dias)
len(lista_dias)
max(lista_dias)
min(lista_dias)
str(10)
int("10")
float("10")
valores = [10>50,60>50,30>50]
all(valores)
any(valores)
filter()
map()
sorted()
zip()